### ISSUE TITLE
Replace 'use 6to5' with 'use babel'

### ISSUE THREAD

**Issue by maxbrunsfeld** [nyteshade/language-geck#1]
Hi @nyteshade; thanks for building and maintaining this package!

In the next Atom release (1.0.8) support for the `'use 6to5'` directive is going to be dropped, in favor of `'use babel'` (or alternatively `/** @babel */`). This is because the `6to5` project has been renamed to `babel`. When you get a chance, please switch your code to use the new directives and publish a new version of your package!

**Comment by Evolution0** [comment]
Fixed by #3

**Comment by nyteshade** [comment]
I must not have been previously receiving emails about issues for this. Sorry I’ve been so silent. To my knowledge nobody was using for found it interesting. Thanks for your work.
